# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 453)
        Form.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 389))
        self.tableWidget.setMaximumSize(QtCore.QSize(639, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 410, 641, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_refresh = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        self.pushButton_uploadFile = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_uploadFile.setObjectName("pushButton_uploadFile")
        self.horizontalLayout.addWidget(self.pushButton_uploadFile)
        self.pushButton_downloadFile = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_downloadFile.setObjectName("pushButton_downloadFile")
        self.horizontalLayout.addWidget(self.pushButton_downloadFile)
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "File transfer system"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Filename"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Filesize"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date"))
        self.pushButton_refresh.setText(_translate("Form", "Refresh"))
        self.pushButton_uploadFile.setText(_translate("Form", "Upload file"))
        self.pushButton_downloadFile.setText(_translate("Form", "Download file"))
        self.pushButton_delete.setText(_translate("Form", "Delete file"))
